
data <- read.table("SWATH/Cell_Study_SRL_1&3_Re_Analysis_for_ET_180409.csv", row.names=1, header=TRUE, sep=',') # 5854 x 111
cols <- colnames(data) # Sample names for the proteins
cols <- gsub("..sample.1..", "", cols)
cols <- gsub(".wiff", "", cols)
cols <- gsub("SM_PC5", "PC5_SM", cols)
cols <- gsub("X1", "1", cols)
cols <- gsub("Sample", "sample", cols)
cols <- gsub("171230_", "", cols)
cols <- gsub("180107_", "", cols)
cols <- gsub("180110_", "", cols)
cols <- gsub("180111_", "", cols)
cols <- gsub("180112_", "", cols)
cols <- gsub("171217_", "", cols)
cols <- gsub("Study",  "study",  cols)
cols <- gsub("Sample", "sample", cols)
cols <- gsub("sample41", "sample_41", cols)
cols <- gsub("sample43", "sample_43", cols)
cols <- gsub("sample49", "sample_49", cols)
cols <- gsub("sample50", "sample_50", cols)
cols <- gsub("sample51", "sample_51", cols)
cols <- gsub("sample52", "sample_52", cols)
cols <- gsub("sample53", "sample_53", cols)
cols <- gsub("sample54", "sample_54", cols)
cols <- gsub("sample56", "sample_56", cols)
cols <- gsub("sample57", "sample_57", cols)
cols <- gsub("sample58", "sample_58", cols)
cols <- gsub("sample72", "sample_72", cols)
cols <- gsub("sample76", "sample_76", cols)
cols <- gsub("sample80", "sample_80", cols)
cols <- gsub("sample81", "sample_81", cols)
cols <- gsub("sample88", "sample_88", cols)
cols <- gsub("sample90", "sample_90", cols)
cols <- gsub("Cell.study", "Cell_study", cols)
cols <- gsub("Cell study", "Cell_study", cols)
cols <- unlist(lapply(strsplit(as.character(cols), "..", fixed=TRUE), '[[', 2))
colnames(data) <- cols

info <- read.table("SWATH/SWATHDetails.csv", row.names=1, header=TRUE, sep=',')
info$ID <- row.names(info)
info <- info[, c("ID", "Sample", "SWATH.Processing.Date", "Acq_Type", "SWATH.Processing.Instrument", "SWATH.File.Name")]
info <- info[with(info, order(Sample, SWATH.File.Name)),]
stopifnot(nrow(info) == length(cols))

info$SWATH.File.Name <- gsub("Study",  "study",  info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("Sample", "sample", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("SM_PC5", "PC5_SM", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("171230_", "", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("180107_", "", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("180110_", "", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("180111_", "", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("180112_", "", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("171217_", "", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub(" Cell", "Cell", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub(" SWATH", "SWATH", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("sample58", "sample_58", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("171230_", "", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("180107_", "", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("180110_", "", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("180111_", "", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("180112_", "", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("SM_PC5", "PC5_SM", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("sample41", "sample_41", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("sample43", "sample_43", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("sample49", "sample_49", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("sample50", "sample_50", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("sample51", "sample_51", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("sample52", "sample_52", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("sample53", "sample_53", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("sample54", "sample_54", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("sample56", "sample_56", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("sample57", "sample_57", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("sample58", "sample_58", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("sample72", "sample_72", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("sample76", "sample_76", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("sample80", "sample_80", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("sample81", "sample_81", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("sample88", "sample_88", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("sample90", "sample_90", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("Cell.study", "Cell_study", info$SWATH.File.Name)
info$SWATH.File.Name <- gsub("Cell study", "Cell_study", info$SWATH.File.Name)

map <- merge(data.frame(Cols=cols), info, by.x="Cols", by.y="SWATH.File.Name")
map <- map[with(map, order(Sample)),]
write.table(map$Sample, file="SWATH/sample.txt", quote=FALSE, row.names=FALSE, col.names=FALSE)

# Run SWATH_CLEANUP.py on Python for mapping the friendly names
map$NewSample <- read.table("SWATH/newSample.txt", header=FALSE, sep="\n")$V1

# Substitue the intensity table with the samples
colnames(data) <- as.character(map$NewSample[match(colnames(data), map$Cols)])

nInfo <- merge(info, map, by.x="ID", by.y="ID")
nInfo <- data.frame(Sample=nInfo$NewSample, Date=nInfo$SWATH.Processing.Date.x, Type=nInfo$Acq_Type.x, Instrument=nInfo$SWATH.Processing.Instrument.x)

write.table(data, file="SWATH/data2.tsv", quote=FALSE, row.names=TRUE, col.names=TRUE, sep="\t")
write.table(nInfo, file="newSWATHDetails.tsv", quote=FALSE, row.names=FALSE, col.names=TRUE, sep="\t")
