
data <- read.table("/Users/twong/Desktop/SWATH/Cell_Study_SRL_1&3_Re_Analysis_for_ET_180409.csv", row.names=1, header=TRUE, sep=',') # 5854 x 111
cols <- colnames(data) # Sample names for the proteins
cols <- gsub("..sample.1..", "", cols)
cols <- gsub(".wiff", "", cols)
cols <- gsub("SM_PC5", "PC5_SM", cols)
cols <- gsub("X1", "1", cols)
cols <- gsub("Sample", "sample", cols)
cols <- gsub("171230_", "", cols)
cols <- gsub("180107_", "", cols)
cols <- gsub("180110_", "", cols)
cols <- gsub("180111_", "", cols)
cols <- gsub("180112_", "", cols)
cols <- gsub("171217_", "", cols)
cols <- gsub("Study",  "study",  cols)
cols <- gsub("Sample", "sample", cols)
cols <- gsub("sample41", "sample_41", cols)
cols <- gsub("sample43", "sample_43", cols)
cols <- gsub("sample49", "sample_49", cols)
cols <- gsub("sample50", "sample_50", cols)
cols <- gsub("sample51", "sample_51", cols)
cols <- gsub("sample52", "sample_52", cols)
cols <- gsub("sample53", "sample_53", cols)
cols <- gsub("sample54", "sample_54", cols)
cols <- gsub("sample56", "sample_56", cols)
cols <- gsub("sample57", "sample_57", cols)
cols <- gsub("sample58", "sample_58", cols)
cols <- gsub("sample72", "sample_72", cols)
cols <- gsub("sample76", "sample_76", cols)
cols <- gsub("sample80", "sample_80", cols)
cols <- gsub("sample81", "sample_81", cols)
cols <- gsub("sample88", "sample_88", cols)
cols <- gsub("sample90", "sample_90", cols)
cols <- gsub("Cell.study", "Cell_study", cols)
cols <- gsub("Cell study", "Cell_study", cols)
cols <- unlist(lapply(strsplit(as.character(cols), "..", fixed=TRUE), '[[', 2))
colnames(data) <- cols

dets <- read.table("/Users/twong/Desktop/SWATH/SWATHDetails.csv", row.names=1, header=TRUE, sep=',')
dets <- dets[, c("Sample", "SWATH.File.Name", "SWATH.file.Location")]
dets <- dets[with(dets, order(Sample, SWATH.File.Name)),]
stopifnot(nrow(det) == length(cols))

dets$SWATH.File.Name <- gsub("Study",  "study",  dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("Sample", "sample", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("SM_PC5", "PC5_SM", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("171230_", "", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("180107_", "", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("180110_", "", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("180111_", "", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("180112_", "", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("171217_", "", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub(" Cell", "Cell", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub(" SWATH", "SWATH", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("sample58", "sample_58", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("171230_", "", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("180107_", "", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("180110_", "", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("180111_", "", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("180112_", "", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("SM_PC5", "PC5_SM", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("sample41", "sample_41", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("sample43", "sample_43", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("sample49", "sample_49", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("sample50", "sample_50", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("sample51", "sample_51", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("sample52", "sample_52", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("sample53", "sample_53", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("sample54", "sample_54", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("sample56", "sample_56", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("sample57", "sample_57", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("sample58", "sample_58", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("sample72", "sample_72", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("sample76", "sample_76", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("sample80", "sample_80", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("sample81", "sample_81", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("sample88", "sample_88", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("sample90", "sample_90", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("Cell.study", "Cell_study", dets$SWATH.File.Name)
dets$SWATH.File.Name <- gsub("Cell study", "Cell_study", dets$SWATH.File.Name)

map <- merge(data.frame(Cols=cols), dets, by.x="Cols", by.y="SWATH.File.Name")
map <- map[with(map, order(Sample)),]
write.table(map$Sample, file="/Users/twong/Sources/RDS-FMH-CWGS-RW/SWATH/sample.txt", quote=FALSE, row.names=FALSE, col.names=FALSE)

# Run SWATH_CLEANUP.py for mapping the friendly names
map$Sample <- read.table("/Users/twong/Sources/RDS-FMH-CWGS-RW/SWATH/newSample.txt", header=FALSE, sep="\n")$V1

colnames(data) <- as.character(map$Sample[match(colnames(data), map$Cols)]) # Substitue the intensity table with the samples
write.table(data, file="/Users/twong/Sources/RDS-FMH-CWGS-RW/SWATH/data2.txt", quote=FALSE, row.names=TRUE, col.names=TRUE)
sort(s <- colnames(data))
print(dim(data))
