#!/bin/bash 

#PBS -l walltime=10:00:00
#PBS -P RDS-FMH-CWGS-RW
#PBS -l select=1:ncpus=1:mem=32GB
#PBS -q defaultQ

REF='/scratch/RDS-FMH-CWGS-RW/Sources/combined.fasta'
OUT='/scratch/RDS-FMH-CWGS-RW/Sources/6'

module load vt

for file in $OUT/*.vcf; do
    echo 'vt decompose -s $file -o $OUT/DECOM_$(basename "$file")'
    vt decompose -s $file -o $OUT/DECOM_$(basename "$file")
    echo 'vt normalize $OUT/DECOM_$(basename "$file") -r $REF -o $OUT/NORM_DECOM_$(basename "$file")'
    vt normalize $OUT/DECOM_$(basename "$file") -r $REF -o $OUT/NORM_DECOM_$(basename "$file")
done
