
#!/bin/bash
# Author: Erdahl Teber

#PBS -N DELLY_DUP_TN
#PBS -l walltime=90:00:0
#PBS -l select=1:ncpus=2:mem=64GB
#PBS -q defaultQ
#PBS -P RDS-SMS-WGS22-RW

DS='/scratch/RDS-SMS-WGS22-RW/RDAGG'
REF='/project/RDS-SMS-WGS22-RW/broad_hg38_canonical_pBABE_puro.fasta'
OX='/scratch/RDS-SMS-WGS22-RW/RDAGG/DELLY'
EX='/project/RDS-SMS-WGS22-RW/human.hg38.excl.tsv'


module load delly

cd /project/RDS-SMS-WGS22-RW

echo $sampleID $controlID $PBS_JOBID $PBS_JOBNAME

prefix='DELLY_DUP'

time /usr/local/delly/0.6.7/bin/delly -t DUP -x $EX -o $OX/${prefix}_${sampleID}.vcf  -g $REF $DS/${sampleID}.bam $DS/${controlID}.bam

