#!/bin/bash

#PBS -l walltime=10:00:00
#PBS -P RDS-FMH-CWGS-RW
#PBS -l select=1:ncpus=1:mem=32GB
#PBS -q defaultQ

module load gatk

java -jar /usr/local/gatk/3.3.0/GenomeAnalysisTK.jar \
-T SelectVariants -R ref.fasta \
-V WI38.vcf -o RAW_SNV_WI38.vcf
-selectType SNP \
--disable_auto_index_creation_and_locking_when_reading_rods

java -jar /usr/local/gatk/3.3.0/GenomeAnalysisTK.jar \
-T VariantFiltration -R ref.fasta \
-V RAW_SNV_WI38.vcf \
-o FILTERED_SNV_WI38.vcf \
--filterExpression "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0" --filterName "my_snp_filter"
