#!/bin/bash

#PBS -l walltime=35:00:00
#PBS -P RDS-FMH-CWGS-RW
#PBS -l select=4:ncpus=8:mem=16GB
#PBS -q defaultQ

DS='/scratch/RDS-FMH-CWGS-RW/Sources/5'
OX='/scratch/RDS-FMH-CWGS-RW/Sources/8'
REF='/scratch/RDS-FMH-CWGS-RW/Sources/combined.fasta'

INPUT=${DS}/REALIGNED_RG_DEDUP_SORTED_HG19_${sampleID}.bam
REFERENCE=$REF
OUTPUT=${OX}/GERMLINE_GRIDSS_${sampleID}.vcf
ASSEMBLY=${OX}/GERMLINE_GRIDSS_${sampleID}.bam

echo $sampleID
cd /scratch/RDS-FMH-CWGS-RW/Sources/8

java -ea -Xmx31g \
	-Dreference_fasta="$REFERENCE" \
	-Dsamjdk.create_index=true \
	-Dsamjdk.use_async_io_read_samtools=true \
	-Dsamjdk.use_async_io_write_samtools=true \
	-Dsamjdk.use_async_io_write_tribble=true \
	-Dgridss.gridss.output_to_temp_file=true \
	-Dgridss.keepTempFiles=true \
	-cp /scratch/RDS-FMH-CWGS-RW/softwares/gridss-1.7.2-gridss-jar-with-dependencies.jar gridss.CallVariants \
	TMP_DIR=. \
	WORKING_DIR=/scratch/RDS-FMH-CWGS-RW/Sources \
	REFERENCE_SEQUENCE="$REFERENCE" \
	INPUT="$INPUT" \
	OUTPUT="$OUTPUT" \
	ASSEMBLY="$ASSEMBLY" \
	2>&1 | tee -a gridss.$HOSTNAME.$$.log
