#!/bin/bash

#PBS -l walltime=120:0:0
#PBS -P RDS-FMH-CWGS-RW
#PBS -l select=16:ncpus=2:mem=32GB
#PBS -q defaultQ

module load gatk

DS='/scratch/RDS-FMH-CWGS-RW/Sources/5'
OX='/scratch/RDS-FMH-CWGS-RW/Sources/6'
REF='/scratch/RDS-FMH-CWGS-RW/Sources/combined.fasta'

echo $sampleID

java -jar /usr/local/gatk/3.3.0/GenomeAnalysisTK.jar -T HaplotypeCaller -nct 32 \
-R       $REF \
-I       $DS/REALIGNED_RG_DEDUP_SORTED_HG19_${sampleID}.bam \
-o       $OX/GATK_${sampleID}.vcf \
--genotyping_mode DISCOVERY -stand_call_conf 30 -stand_emit_conf 10
