#!/bin/bash

#PBS -l walltime=120:0:0
#PBS -P RDS-FMH-CWGS-RW
#PBS -l select=1:ncpus=3:mem=64GB
#PBS -q defaultQ

module load gatk

DS='/scratch/RDS-FMH-CWGS-RW/Sources/5'
OX='/scratch/RDS-FMH-CWGS-RW/Sources/6'
REF='/scratch/RDS-FMH-CWGS-RW/combined.fasta'

echo $sampleID $PBS_JOBID $PBS_JOBNAME

java -jar /usr/local/gatk/3.3.0/GenomeAnalysisTK.jar -T HaplotypeCaller \
-R       $REF \
-I       $DS/${sampleID}.bam \
-o       $OX/GATK_${sampleID}.vcf \
--genotyping_mode DISCOVERY -stand_call_conf 30 -stand_emit_conf 10
