#!/bin/bash

#PBS -l walltime=100:0:0
#PBS -P RDS-FMH-CWGS-RW
#PBS -l select=1:ncpus=2:mem=64GB
#PBS -q defaultQ

module load mutect

DS='/scratch/RDS-FMH-CWGS-RW/5'
REF='/scratch/RDS-FMH-CWGS-RW/Sources/combined.fasta'
OT='/scratch/RDS-FMH-CWGS-RW/Sources/7'

echo $sampleID $controlID $PBS_JOBID $PBS_JOBNAME

/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.34.x86_64/bin/java -jar /usr/local/mutect/1.1.4/muTect-1.1.4.jar --analysis_type MuTect \
--reference_sequence  $REF \
--input_file:tumor  $DS/$sampleID.bam \
--input_file:normal $DS/$controlID.bam \
--out    $OT/MUTECT_${sampleID}.call_out \
--coverage_file  $OT/MUTECT_${sampleID}.coverages.wig.txt \
--enable_extended_output \
--vcf    $OT/MUTECT_${sampleID}.vcf 
