#!/bin/bash

#PBS -l walltime=100:0:0
#PBS -P RDS-FMH-CWGS-RW
#PBS -l select=4:ncpus=8:mem=16GB
#PBS -q defaultQ

module load mutect

DS='/scratch/RDS-FMH-CWGS-RW/Sources/5'
REF='/scratch/RDS-FMH-CWGS-RW/Sources/combined.fasta'
OT='/scratch/RDS-FMH-CWGS-RW/Sources/7'

echo $sampleID $controlID $PBS_JOBID $PBS_JOBNAME

/scratch/RDS-FMH-CWGS-RW/softwares/gatk-4.0.4.0/gatk Mutect2 -R $REF \
-I $DS/RG_DEDUP_SORTED_HG19_$tumorID.bam -tumor $tumorID \
-I $DS/RG_DEDUP_SORTED_HG19_$normalID.bam -normal $normalID \
--native-pair-hmm-threads 32 -O $OT/MUTECT_${tumorID}.vcf
