#!/bin/bash

#PBS -l walltime=48:00:00
#PBS -P RDS-FMH-CWGS-RW
#PBS -l select=4:ncpus=4:mem=16GB
#PBS -q defaultQ

DS='/scratch/RDS-FMH-CWGS-RW/Sources/5'
REF='/scratch/RDS-FMH-CWGS-RW/Sources/combined.fasta'
OT='/scratch/RDS-FMH-CWGS-RW/Sources/7'

echo $normalID $tumorID $PBS_JOBID $PBS_JOBNAME

ls -la $DS/RG_DEDUP_SORTED_HG19_$normalID.bam
ls -la $DS/RG_DEDUP_SORTED_HG19_$tumorID.bam

/scratch/RDS-FMH-CWGS-RW/softwares/gatk-4.0.4.0/gatk Mutect2 -R $REF \
-I $DS/RG_DEDUP_SORTED_HG19_$tumorID.bam -tumor SAMPLE_$tumorID \
-I $DS/RG_DEDUP_SORTED_HG19_$normalID.bam -normal SAMPLE_$normalID \
--native-pair-hmm-threads 32 -O $OT/MUTECT_${tumorID}.vcf
