CREATE TABLE Annotation (
	Key   			   VARCHAR(50) NOT NULL,
	File  			   VARCHAR(50) NOT NULL,
	DP    			   VARCHAR(50) NOT NULL,
	AD_1  			   VARCHAR(50) NOT NULL,
	AD_2  			   VARCHAR(50), -- NULL if not two samples
	AF_1  			   VARCHAR(50) NOT NULL,
	AF_2  			   VARCHAR(50), -- NULL if not two samples
	GT_1  			   VARCHAR(50) NOT NULL,
	GT_2  			   VARCHAR(50), -- NULL if not two samples
	QL_1  			   VARCHAR(50) NOT NULL,
	QL_2  			   VARCHAR(50), -- NULL if not two samples
    Chrom 			   VARCHAR(50) NOT NULL,
    POS  			   VARCHAR(50) NOT NULL,
    REF   			   VARCHAR(50) NOT NULL,
    ALT   			   VARCHAR(50) NOT NULL,
	Allele 		  	   VARCHAR(50), 
	Consequence   	   VARCHAR(50), 
	IMPACT 		  	   VARCHAR(50), 
	SYMBOL 		  	   VARCHAR(50), 
	Gene 		  	   VARCHAR(50), 
	Feature_type  	   VARCHAR(50), 
	Feature 	  	   VARCHAR(50), 
	BIOTYPE		  	   VARCHAR(50), 
	EXON  		  	   VARCHAR(50),
	INTRON  		   VARCHAR(50),	 
	HGVSc  		  	   VARCHAR(50),
	HGVSp  		  	   VARCHAR(50),	
	cDNA_position	   VARCHAR(50),
	CDS_position  	   VARCHAR(50),
	Protein_position   VARCHAR(50), 
	Amino_acids 	   VARCHAR(50), 
	Codons 			   VARCHAR(50), 
	Existing_variation VARCHAR(50), 
	DISTANCE 		   VARCHAR(50), 
	STRAND 			   VARCHAR(50),
	FLAGS 			   VARCHAR(50), 
	VARIANT_CLASS 	   VARCHAR(50), 
	SYMBOL_SOURCE 	   VARCHAR(50), 
	HGNC_ID 		   VARCHAR(50), 
	CANONICAL 		   VARCHAR(50), 
	TSL 			   VARCHAR(50), 
	APPRIS 			   VARCHAR(50), 
	CCDS 			   VARCHAR(50), 
	ENSP 			   VARCHAR(50), 
	SWISSPROT 		   VARCHAR(50), 
	TREMBL 			   VARCHAR(50), 
	UNIPARC 		   VARCHAR(50), 
	GENE_PHENO 		   VARCHAR(50),
	SIFT 			   VARCHAR(50), 
	PolyPhen 		   VARCHAR(50),
	DOMAINS 		   VARCHAR(50), 
	miRNA 			   VARCHAR(50),
	AF 				   VARCHAR(50), 
	AFR_AF 			   VARCHAR(50),
	AMR_AF 			   VARCHAR(50),
	EAS_AF 			   VARCHAR(50),
	EUR_AF 			   VARCHAR(50),
	SAS_AF 			   VARCHAR(50), 
    AA_AF 			   VARCHAR(50),
	EA_AF 			   VARCHAR(50), 
	gnomAD_AF 		   VARCHAR(50), 		 
	gnomAD_AFR_AF 	   VARCHAR(50),
	gnomAD_AMR_AF 	   VARCHAR(50), 
	gnomAD_ASJ_AF      VARCHAR(50), 
	gnomAD_EAS_AF      VARCHAR(50), 
	gnomAD_FIN_AF      VARCHAR(50), 
 	gnomAD_NFE_AF      VARCHAR(50), 
	gnomAD_OTH_AF      VARCHAR(50), 
	gnomAD_SAS_AF      VARCHAR(50), 
	MAX_AF 		       VARCHAR(50), 
	MAX_AF_POPS 	   VARCHAR(50), 
	CLIN_SIG 		   VARCHAR(50), 
	SOMATIC 		   VARCHAR(50), 
	PHENO 			   VARCHAR(50), 		  
	PUBMED 			   VARCHAR(50), 
	MOTIF_NAME 		   VARCHAR(50),
	MOTIF_POS 		   VARCHAR(50), 
	HIGH_INF_POS 	   VARCHAR(50), 
	MOTIF_SCORE_CHANGE VARCHAR(50)
);