#!/bin/bash

#PBS -l walltime=10:00:00
#PBS -P RDS-FMH-CWGS-RW
#PBS -l select=1:ncpus=1:mem=32GB
#PBS -q defaultQ

IX='/scratch/RDS-FMH-CWGS-RW/Sources/6'
OX='/scratch/RDS-FMH-CWGS-RW/Sources/6'

for file in $IX/FILTERED_*vcf; do
    java -jar /usr/local/gatk/3.3.0/GenomeAnalysisTK.jar \
         -T SelectVariants \
         -R /scratch/RDS-FMH-CWGS-RW/Sources/combined.fasta \
         -V $IX/$(basename "$file") \
         -o $OX/REMOVED_$(basename "$file") \
         --excludeFiltered
done
