#!/bin/bash

#PBS -l walltime=10:00:00
#PBS -P RDS-FMH-CWGS-RW
#PBS -l select=1:ncpus=1:mem=32GB
#PBS -q defaultQ

REF='/scratch/RDS-FMH-CWGS-RW/Sources/combined.fasta'
IX='/scratch/RDS-FMH-CWGS-RW/Sources/7'
OX='/scratch/RDS-FMH-CWGS-RW/Sources/7'

for file in $IX/NORM_MUTECT_*.vcf; do
    /scratch/RDS-FMH-CWGS-RW/softwares/gatk-4.0.4.0/gatk VariantFiltration \
         -V $IX/$file -O OX/FILTERED_$file \
         --filter-expression "DP >= 10" --filter-name "MuTectFilter" -O FILTERED_MUTECT_IIICF_d2.vcf         
done
