#!/bin/bash

#PBS -l walltime=10:00:00
#PBS -P RDS-FMH-CWGS-RW
#PBS -l select=1:ncpus=1:mem=32GB
#PBS -q defaultQ

IX='/home/twong/das_manual/Process/Bioinformatics/tedwong/RDS-FMH-CWGS-RW/7'
OX='/home/twong/das_manual/Process/Bioinformatics/tedwong/RDS-FMH-CWGS-RW/7'

for file in $IX/NORM_MUTECT_*.vcf; do
    /scratch/RDS-FMH-CWGS-RW/softwares/gatk-4.0.4.0/gatk FilterMutectCalls \
         -V $IX/$(basename "$file") -O $OX/FILTERED_$(basename "$file")     
done
