#!/bin/bash

#PBS -l walltime=00:01:00
#PBS -P RDS-FMH-CWGS-RW
#PBS -l select=1:ncpus=1:mem=128GB
#PBS -q defaultQ

cd /scratch/RDS-FMH-CWGS-RW/RDS-FMH-CWGS-RW

#GENOME=combined.fasta
#PICARD=/home/twon2259/Sources/picard.jar

#java -jar $PICARD CreateSequenceDictionary R=$GENOME O=combined.dict
java -jar /scratch/RDS-FMH-CWGS-RW/softwares/picard.jar CreateSequenceDictionary \
REFERENCE=/scratch/RDS-FMH-CWGS-RW/softwares/combined.fasta OUTPUT=/scratch/RDS-FMH-CWGS-RW/softwares/combined.dict
