#!/bin/bash
# Author: Erdahl Teber and Ted Wong

#PBS -N INDEX_hg38
#PBS -l walltime=15:00:00
#PBS -P RDS-SMS-CMRIWGS-RW
#PBS -l select=1:ncpus=2:mem=64GB
#PBS -q defaultQ

cd /scratch/RDS-SMS-WGS22-RW

PD='/usr/local/picard/1.119'
REF='/project/RDS-SMS-WGS22-RW/broad_hg38_canonical_with_vectors.fasta'
DS='/scratch/RDS-SMS-WGS22-RW/HG38_PROJECT'

short_name=$sampleID
echo $sampleID 

time java -jar $PD/BuildBamIndex.jar INPUT=$DS/RG_DEDUP_SORTED_HG38_${short_name}.bam OUTPUT=$DS/RG_DEDUP_SORTED_HG38_${short_name}.bai
