#!/bin/bash

#PBS -l walltime=15:00:00
#PBS -P RDS-FMH-CWGS-RW 
#PBS -l select=1:ncpus=2:mem=64GB
#PBS -q defaultQ

cd /scratch/RDS-FMH-CWGS-RW/Sources

PD='/scratch/RDS-FMH-CWGS-RW/softwares'
REF='/scratch/RDS-FMH-CWGS-RW/Sources/combined.fasta'
DS='/scratch/RDS-FMH-CWGS-RW/5'

short_name=$sampleID
echo $sampleID 

java -jar $PD/picard.jar BuildBamIndex INPUT=$DS/RG_DEDUP_SORTED_HG38_${short_name}.bam OUTPUT=$DS/RG_DEDUP_SORTED_HG38_${short_name}.bai
