#!/bin/bash
# Author: Erdahl Teber

#PBS -l walltime=35:00:00
#PBS -P RDS-FMH-CWGS-RW
#PBS -l select=1:ncpus=2:mem=64GB
#PBS -q defaultQ


cd /scratch/RDSRDS-FMH-CWGS-RW/Source

WD='/project/RDS-SMS-WGS22-RW'
REF='/project/RDS-SMS-WGS22-RW/broad_hg38_canonical_with_vectors.fasta'
DS='/scratch/RDS-SMS-WGS22-RW/HG38_PROJECT'
GT='/usr/local/gatk/3.3.0'

short_name=$sampleID
echo $sampleID

time java -jar  $GT/GenomeAnalysisTK.jar -T RealignerTargetCreator \
-R  $REF \
-I $DS/RG_DEDUP_SORTED_HG38_${short_name}.bam \
-o $DS/RG_DEDUP_SORTED_HG38_${short_name}.intervals \
--known $WD/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz \
--known $WD/Homo_sapiens_assembly38.known_indels.vcf.gz \
-log $DS/RG_DEDUP_SORTED_HG38_${short_name}.interval.log

