#!/bin/bash

#PBS -l walltime=35:00:00
#PBS -P RDS-FMH-CWGS-RW
#PBS -l select=1:ncpus=2:mem=64GB
#PBS -q defaultQ

cd /scratch/RDS-FMH-CWGS-RW/Sources

WD='/scratch/RDS-FMH-CWGS-RW/softwares'
REF='/scratch/RDS-FMH-CWGS-RW/Sources/combined.fasta'
DS='/scratch/RDS-FMH-CWGS-RW/Sources/5'
GT='/usr/local/gatk/3.8.1'

short_name=$sampleID
echo $sampleID

java -jar $GT/GenomeAnalysisTK.jar -T RealignerTargetCreator \
-R  $REF \
-I $DS/RG_DEDUP_SORTED_HG19_${short_name}.bam \
-o $DS/RG_DEDUP_SORTED_HG19_${short_name}.intervals \
--known $WD/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf.gz \ 
-log $DS/RG_DEDUP_SORTED_HG19_${short_name}.interval.log

#--known $WD/Homo_sapiens_assembly38.known_indels.vcf.gz \  Can't find for HG38
