#!/bin/bash

#PBS -l walltime=35:00:00
#PBS -P RDS-FMH-CWGS-RW
#PBS -l select=1:ncpus=2:mem=64GB
#PBS -q defaultQ

cd /scratch/RDS-FMH-CWGS-RW/Sources

REF='/scratch/RDS-FMH-CWGS-RW/Sources/combined.fasta'
DS='/scratch/RDS-FMH-CWGS-RW/Sources/combined.fasta/5'
GT='/usr/local/gatk/3.3.0'

short_name=$sampleID
echo $sampleID 

time java -jar $GT/GenomeAnalysisTK.jar -T IndelRealigner \
-R $REF \
-I $DS/RG_DEDUP_SORTED_HG19_${short_name}.bam \
-o $DS/REALIGNED_RG_DEDUP_SORTED_HG19_${short_name}.bam \
-targetIntervals $DS/RG_DEDUP_SORTED_HG19_${short_name}.intervals

