#!/bin/bash

#PBS -l walltime=20:00:00
#PBS -P RDS-FMH-CWGS-RW
#PBS -l select=1:ncpus=2:mem=64GB
#PBS -q defaultQ

cd /scratch/RDS-FMH-CWGS-RW/Sources

PD='/scratch/RDS-FMH-CWGS-RW/softwares/picard.jar'
REF='/scratch/RDS-FMH-CWGS-RW/Sources/combined.fasta'
DS='/scratch/RDS-FMH-CWGS-RW/Sources/5'

short_name=$sampleID
echo $sampleID

java -jar $PD BuildBamIndex INPUT=$DS/REALIGNED_RG_DEDUP_SORTED_HG19_${short_name}.bam OUTPUT=$DS/REALIGNED_RG_DEDUP_SORTED_HG19_${short_name}.bai
