#!/bin/bash
# Author: Erdahl Teber

#PBS -l walltime=25:00:00
#PBS -P RDS-FMH-CWGS-RW
#PBS -l select=2:ncpus=4:mem=32GB
#PBS -q defaultQ

TRM='/scratch/RDS-FMH-CWGS-RW/softwares/Trimmomatic-0.36'
OX='/scratch/RDS-FMH-CWGS-RW/Sources/2'
IX='/scratch/RDS-FMH-CWGS-RW/Sources/RawFiles'

short_name=$sm
echo $sampleID 

time java -jar $TRM/trimmomatic-0.36.jar PE -threads 8 -phred33 $IX/${short_name}_R1.fastq.gz $IX/${short_name}_R2.fastq.gz \
$OX/F1_PAIRED_${short_name}.fq $OX/F1_UNPAIRED_${short_name}.fq \
$OX/F2_PAIRED_${short_name}.fq $OX/F2_UNPAIRED_${short_name}.fq \
ILLUMINACLIP:TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:75 2> $OX/TRIMMOMATIC_${short_name}.log
