#!/bin/bash

#PBS -l walltime=25:00:00
#PBS -P RDS-FMH-CWGS-RW
#PBS -l select=2:ncpus=4:mem=32GB
#PBS -q defaultQ

TRIM='/home/twon2259/Sources/Trimmomatic-0.36'
OX='/scratch/RDS-FMH-CWGS-RW/RDS-FMH-CWGS-RW/trimmed'
IX='/scratch/RDS-FMH-CWGS-RW/large_files/1803KHX-0015_hdd1'

sample=$sampleID
echo $sampleID 

time java -jar $TRIM/trimmomatic-0.36.jar PE -threads 8 -phred33 $IX/${sample}/${sample}_R1.fastq.gz \
    $IX/${sample}/${sample}_R2.fastq.gz \
    $OX/F1_PAIRED_${sample}.fastq.gz $OX/F1_UNPAIRED_${sample}.fastq.gz \
    $OX/F2_PAIRED_${sample}.fastq.gz $OX/F2_UNPAIRED_${sample}.fastq.gz \
    ILLUMINACLIP:TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:75 2> $OX/TRIMMOMATIC_${sample}.log
