#!/bin/bash
# Author: Erdahl Teber

#PBS -N TRIM_hg38
#PBS -l walltime=25:00:00
#PBS -P RDS-SMS-CMRIWGS-RW
#PBS -l select=2:ncpus=4:mem=32GB
#PBS -q defaultQ

cd /scratch/RDS-SMS-WGS22-RW

TRM='/scratch/RDS-FMH-CWGS-RW/softwares/Trimmomatic-0.36'
OX='/scratch/RDS-FMH-CWGS-RW/Sources/2'
IX='/scratch/RDS-FMH-CWGS-RW/large_files/1803KHX-0015_hdd1'

short_name=$sm
echo $sampleID 

echo $IX/${short_name}_R1.fq.gz
echo $IX/${short_name}_R2.fq.gz
echo $OX/F1_PAIRED_${short_name}.fq
echo $OX/F1_UNPAIRED_${short_name}.fq
echo $OX/TRIMMOMATIC_${short_name}.log

#time java -jar $TRM/trimmomatic-0.33.jar PE -threads 8 -phred33 $IX/${short_name}_R1.fq.gz $IX/${short_name}_R2.fq.gz \
#$OX/F1_PAIRED_${short_name}.fq $OX/F1_UNPAIRED_${short_name}.fq \
#$OX/F2_PAIRED_${short_name}.fq $OX/F2_UNPAIRED_${short_name}.fq \
#ILLUMINACLIP:TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:75 2> $OX/TRIMMOMATIC_${short_name}.log
