#!/bin/bash

#PBS -l walltime=35:00:00
#PBS -P RDS-FMH-CWGS-RW
#PBS -l select=4:ncpus=4:mem=16GB
#PBS -q defaultQ

module load samtools

DS='/scratch/RDS-FMH-CWGS-RW/Sources/2'
REF='/scratch/RDS-FMH-CWGS-RW/Sources/combined.fasta'
OX='/scratch/RDS-FMH-CWGS-RW/Sources/4'

short_name=$sm

/scratch/RDS-FMH-CWGS-RW/softwares/bwa-0.7.17/bwa mem -t 14 -M $REF $DS/F1_PAIRED_${short_name}.fq $DS/F2_PAIRED_${short_name}.fq | samtools view -bS - | samtools sort -@ 2 > $OX/HG38_${short_name}.bam
