#!/bin/bash
# Author: Erdahl Teber

#PBS -N SORT_hg38
#PBS -l walltime=30:00:00
#PBS -P RDS-SMS-CMRIWGS-RW
#PBS -l select=1:ncpus=2:mem=64GB
#PBS -q defaultQ

cd /scratch/RDS-SMS-WGS22-RW

PD='/usr/local/picard/1.119'
DS='/scratch/RDS-SMS-WGS22-RW/HG38_PROJECT'
REF='/project/RDS-SMS-WGS22-RW/broad_38_canonical.fasta'

short_name=$sampleID
echo $sampleID

time java -jar $PD/SortSam.jar INPUT=$DS/HG38_${short_name}.sam OUTPUT=$DS/SORTED_HG38_${short_name}.bam SORT_ORDER=coordinate


