#!/bin/bash

#PBS -l walltime=30:00:00
#PBS -P RDS-FMH-CWGS-RW
#PBS -l select=1:ncpus=2:mem=64GB
#PBS -q defaultQ

cd /scratch/RDS-FMH-CWGS-RW

PD='/scratch/RDS-FMH-CWGS-RW/softwares'
REF='/scratch/RDS-FMH-CWGS-RW/Sources/combined.fasta'
DS='/scratch/RDS-FMH-CWGS-RW/Sources/4'

short_name=$sampleID
echo $sampleID 

java -jar $PD/MarkDuplicates.jar INPUT=$DS/SORTED_HG38_${short_name}.bam OUTPUT=$DS/DEDUP_SORTED_HG38_${short_name}.bam \
REMOVE_DUPLICATES=FALSE VALIDATION_STRINGENCY=LENIENT ASSUME_SORTED=TRUE CREATE_INDEX=TRUE METRICS_FILE=$DS/METRICS_DEDUP_SORTED_HG38_${short_name}.txt

