#!/bin/bash
# Author: Erdahl Teber and Ted Wong

#PBS -N DSORT_hg38
#PBS -l walltime=00:02:00
#PBS -P RDS-SMS-CMRIWGS-RW
#PBS -l select=1:ncpus=1
#PBS -q defaultQ


cd /scratch/RDS-SMS-WGS22-RW

PD='/usr/local/picard/1.119'
REF='/project/RDS-SMS-WGS22-RW/broad_38_canonical.fasta'
DS='/scratch/RDS-SMS-WGS22-RW/HG38_PROJECT'

short_name=$sampleID
echo $sampleID 

rm $DS/SORTED_HG38_${short_name}.bam
