#!/bin/bash

#PBS -l walltime=40:00:00
#PBS -P RDS-FMH-CWGS-RW
#PBS -l select=1:ncpus=2:mem=64GB
#PBS -q defaultQ

cd /scratch/RDS-FMH-CWGS-RW/Sources 

PD='/scratch/RDS-FMH-CWGS-RW/softwares'
REF='/scratch/RDS-FMH-CWGS-RW/Sources/combined.fasta'
DS='/scratch/RDS-FMH-CWGS-RW/Sources/5'

short_name=$sampleID
echo $sampleID 

supplier='MGEN_GARVAN'
rg_sample_name='SAMPLE_'
lib_name='NA_'

java -jar $PD/picard.jar AddOrReplaceReadGroups INPUT=$DS/DEDUP_SORTED_HG38_${short_name}.bam OUTPUT=$DS/RG_DEDUP_SORTED_HG38_${short_name}.bam \
RGID=${short_name} RGLB=${lib_name}${short_name} RGPL=ILLUMINA RGPU=$supplier RGSM=${rg_sample_name}${short_name}
