FROM openjdk

RUN apt-get update
RUN wget http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/Trimmomatic-0.36.zip
RUN unzip Trimmomatic-0.36.zip
RUN java -jar Trimmomatic-0.36/trimmomatic-0.36.jar 
