
scp twon2259@hpc:/scratch/RDS-FMH-CWGS-RW/Sources/5/REALIGNED_RG_DEDUP_SORTED_HG19_IIICF.bam* 5/
scp twon2259@hpc:/scratch/RDS-FMH-CWGS-RW/Sources/5/REALIGNED_RG_DEDUP_SORTED_HG19_IIICF-E6E7_A1.bam* 5/
scp twon2259@hpc:/scratch/RDS-FMH-CWGS-RW/Sources/5/REALIGNED_RG_DEDUP_SORTED_HG19_IIICF-T_B1.bam* 5/
scp twon2259@hpc:/scratch/RDS-FMH-CWGS-RW/Sources/5/REALIGNED_RG_DEDUP_SORTED_HG19_IIICF-T_B3.bam* 5/
scp twon2259@hpc:/scratch/RDS-FMH-CWGS-RW/Sources/5/REALIGNED_RG_DEDUP_SORTED_HG19_IIICF-T_C3.bam* 5/
scp twon2259@hpc:/scratch/RDS-FMH-CWGS-RW/Sources/5/REALIGNED_RG_DEDUP_SORTED_HG19_IIICF-T_C4.bam* 5/
