#!/bin/bash

module load gi/R
module load gi/java

bwa

DS="/share/ScratchGeneral/tedwon/RDS-FMH-CWGS-RW/5"
OX="/share/ScratchGeneral/tedwon/RDS-FMH-CWGS-RW/8"
REF="/share/ScratchGeneral/tedwon/RDS-FMH-CWGS-RW/combined.fasta"

NORMAL=${DS}/REALIGNED_RG_DEDUP_SORTED_HG19_$1.bam
TUMOR=${DS}/REALIGNED_RG_DEDUP_SORTED_HG19_$2.bam

REFERENCE=$REF
OUTPUT=${OX}/SOMATIC_GRIDSS_$2.vcf
ASSEMBLY=${OX}/SOMATIC_GRIDSS_$2.bam

echo ${DS}
echo ${OS}
echo ${OUTPUT}
echo ${ASSEMBLY}

cd /share/ScratchGeneral/tedwon/RDS-FMH-CWGS-RW

java -ea -Xmx32g \
	-Dsamjdk.create_index=true \
	-Dgridss.defensiveGC=true \
	-Dsamjdk.use_async_io_read_samtools=true \
	-Dsamjdk.use_async_io_write_samtools=true \
	-Dsamjdk.use_async_io_write_tribble=true \
	-Dsamjdk.compression_level=1 \
	-cp gridss-1.7.2-gridss-jar-with-dependencies.jar gridss.CallVariants \
	TMP_DIR=/share/ScratchGeneral/tedwon/RDS-FMH-CWGS-RW/8 \
	WORKING_DIR=/share/ScratchGeneral/tedwon/RDS-FMH-CWGS-RW/8 \
	REFERENCE_SEQUENCE="$REFERENCE" \
	WORKER_THREADS=4 \
	INPUT="$NORMAL" \
	INPUT="$TUMOR" \
	OUTPUT="$OUTPUT" \
	ASSEMBLY="$ASSEMBLY" \
	2>&1 | tee -a gridss.somatic.$HOSTNAME.$$.log
