#!/bin/bash

module load gi/java
module load gi/R

DS="/scratch/RDS-FMH-CWGS-RW/Sources/5"
OX="/scratch/RDS-FMH-CWGS-RW/Sources/8"
REF="/scratch/RDS-FMH-CWGS-RW/Sources/combined.fasta"

NORMAL=${DS}/REALIGNED_RG_DEDUP_SORTED_HG19_$1.bam
TUMOR=${DS}/REALIGNED_RG_DEDUP_SORTED_HG19_$2.bam

REFERENCE=$REF
OUTPUT=${OX}/SOMATIC_GRIDSS_$2.vcf
ASSEMBLY=${OX}/SOMATIC_GRIDSS_$2.bam

cd /share/ScratchGeneral/tedwon/RDS-FMH-CWGS-RW

java -ea -Xmx64g \
	-Dsamjdk.create_index=true \
	-Dgridss.defensiveGC=true \
	-Dsamjdk.use_async_io_read_samtools=true \
	-Dsamjdk.use_async_io_write_samtools=true \
	-Dsamjdk.use_async_io_write_tribble=true \
	-Dsamjdk.compression_level=1 \
	-cp gridss-1.7.2-gridss-jar-with-dependencies.jar gridss.CallVariants \
	TMP_DIR=/share/ScratchGeneral/tedwon/RDS-FMH-CWGS-RW/8 \
	WORKING_DIR=/share/ScratchGeneral/tedwon/RDS-FMH-CWGS-RW/8 \
	REFERENCE_SEQUENCE="$REFERENCE" \
	INPUT="$NORMAL" \
	INPUT="$TUMOR" \
	OUTPUT="$OUTPUT" \
	ASSEMBLY="$ASSEMBLY" \
	2>&1 | tee -a gridss.somatic.$HOSTNAME.$$.log
