#!/bin/bash

#PBS -l walltime=48:00:00
#PBS -P RDS-FMH-CWGS-RW
#PBS -l select=1:ncpus=1:mem=32GB
#PBS -q defaultQ

module load R
module load bwa
module load java
module load samtools
which bwa

DS='/scratch/RDS-FMH-CWGS-RW/Sources/5'
OX='/scratch/RDS-FMH-CWGS-RW/Sources/8'
REF='/scratch/RDS-FMH-CWGS-RW/Sources/combined.fasta'

SAMPLE=${DS}/REALIGNED_RG_DEDUP_SORTED_HG19_${sample}.bam

REFERENCE=$REF
OUTPUT=${OX}/SOMATIC_GRIDSS_${sample}.vcf
ASSEMBLY=${OX}/SOMATIC_GRIDSS_${sample}.bam

cd /scratch/RDS-FMH-CWGS-RW/Sources/8
java -Xmx128g \
	-cp /scratch/RDS-FMH-CWGS-RW/softwares/gridss-1.7.2-gridss-jar-with-dependencies.jar gridss.CallVariants \
	REFERENCE_SEQUENCE="$REFERENCE" \
	INPUT="$SAMPLE" \
	OUTPUT="$OUTPUT" \
	ASSEMBLY="$ASSEMBLY" \
	2>&1 | tee -a gridss.somatic.$HOSTNAME.$$.log
